kind = "web"
previewPath = "/"
title = "Godlex SMP"
version = "1.0.0"
id = "artifacts/godlex-smp"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24177

[services.development]
run = "pnpm --filter @workspace/godlex-smp run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/godlex-smp", "run", "build" ]
publicDir = "artifacts/godlex-smp/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24177"
BASE_PATH = "/"
